---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-page
  namespace: ingress-nginx
spec:
  selector:
    matchLabels:
      app: default-page
  template:
    metadata:
      labels:
        app: default-page
    spec:
      containers:
        - name: nginx
          image: "nginx:1.17-alpine"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: default-page
  namespace: ingress-nginx
spec:
  selector:
    app: default-page
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: default-page
  namespace: ingress-nginx
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: default-page
              servicePort: 80
